// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEcommerceAPI.Data;

namespace ProjetoEcommerceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230215141738_Criandoproduto")]
    partial class Criandoproduto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeDaCategoria")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("StatusDaCategoria")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AlturaDoProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("CentroDeDistribuicao")
                        .HasColumnType("text");

                    b.Property<decimal>("ComprimentoDoProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DataCriacaoDoProduto")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataModificacaoDoProduto")
                        .HasColumnType("datetime");

                    b.Property<string>("DescricaoDoProduto")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<decimal>("LarguraDoProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NomeDoProduto")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("PesoDoProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("QuantidadeEmEstoqueDoProduto")
                        .HasColumnType("int");

                    b.Property<bool>("StatusDoProduto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDoProduto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("SubCategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.SubCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("datetime");

                    b.Property<string>("NomeDaSubCategoria")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("StatusDaSubCategoria")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategorias");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.Produto", b =>
                {
                    b.HasOne("ProjetoEcommerceAPI.Controllers.Models.SubCategoria", "SubCategoria")
                        .WithMany("Produtos")
                        .HasForeignKey("SubCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.SubCategoria", b =>
                {
                    b.HasOne("ProjetoEcommerceAPI.Controllers.Models.Categoria", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.Categoria", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("ProjetoEcommerceAPI.Controllers.Models.SubCategoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
